### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by ACz-UniBi** [openaire/Generic-Matomo-Tracker#1]
based on Ubuntu 19.04, I follow the README steps and get the following msg:

```
(matomo_tracker) Generic-Analytics-Tracker$ /usr/bin/python2.7 matomo_import_logs.py /var/log/nginx
Traceback (most recent call last):
  File "matomo_import_logs.py", line 1567, in <module>
    config = Configuration()
  File "matomo_import_logs.py", line 440, in __init__
    self._parse_args(self._create_parser())
  File "matomo_import_logs.py", line 415, in _create_parser
    matomoConfig=yaml.load(stream, Loader=yaml.FullLoader)
AttributeError: 'module' object has no attribute 'FullLoader'
```

Any idea's?

Thanks in advance, Andreas

**Comment by dimitrispie** [comment]
Can you try this workout?

https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

**Comment by ACz-UniBi** [comment]
sure, here the results:

```
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version__
'5.1.1'
>>> 
```
